---
- hosts: all
  sudo: yes
  tasks:
    # Terminal coloring
    - name: move .bashrc
      copy: src=files/bashrc dest=/home/vagrant/.bashrc force=yes

    - name: source .bashrc
      raw: source /home/vagrant/.bashrc

    # Unzip
    - name: install unzip
      apt: pkg=unzip state=latest

    # Java
    - name: install java
      apt: pkg=openjdk-7-jdk state=latest

    - name: make /usr/java directory
      file: dest=/usr/java state=directory

    - name: link java to /usr/java/default
      file: src=/usr/lib/jvm/java-7-openjdk-amd64 dest=/usr/java/default state=link

    # Apache 2
    - name: ensure apache2 is at the latest version
      apt: pkg=apache2 state=latest
      notify:
      - restart apache2

    # Solr
    - name: download solr-4.2.1
      sudo: no
      local_action: get_url url=https://archive.apache.org/dist/lucene/solr/4.2.1/solr-4.2.1.tgz dest=files/solr-4.2.1.tgz

    - name: install solr-4.2.1
      unarchive: src=files/solr-4.2.1.tgz dest=/opt

    - name: move schema.xml
      copy: src=files/schema.xml dest=/opt/solr-4.2.1/example/solr/collection1/conf

    - name: move solrconfig.xml
      copy: src=files/solrconfig.xml dest=/opt/solr-4.2.1/example/solr/collection1/conf

    - name: make data/index directory
      file: dest=/opt/solr-4.2.1/example/solr/collection1/data/index state=directory

    - name: move solr files
      copy: src={{ item }} dest=/opt/solr-4.2.1/example/solr/collection1/data/index
      with_fileglob:
        - files/solr/*

    # Specify Web Portal
    - name: download specify web portal
      sudo: no
      local_action: get_url url=http://update.specifysoftware.org/TheSpecifyWebPortal.zip dest=files/TheSpecifyWebPortal.zip

    - name: install specify web portal
      unarchive: src=files/TheSpecifyWebPortal.zip dest=/tmp

    - name: move specify web portal files
      command: /bin/cp -R /tmp/PortalApp/* /var/www/html

    - name: move settings.json
      copy: src=files/settings.json dest=/var/www/html/resources/config

    - name: move fldmodel.json
      copy: src=files/flds.json dest=/var/www/html/resources/config/fldmodel.json

    - name: move and start specify-web-portal service
      copy: src=files/specify-web-portal.conf dest=/etc/init/specify-web-portal.conf mode=0644
      notify:
      - restart specify-web-portal

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart specify-web-portal
      service: name=specify-web-portal state=restarted
